# Generated by Django 5.1.1 on 2024-09-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('esal', models.FloatField()),
            ],
        ),
    ]
